Repository Discord4J/Discord4J, pull requests merged in 2019-02, with the labels that each got.

#474 Add documented audit log reason length constant
  core/src/main/java/discord4j/core/object/audit/AuditLogEntry.java
Labels: v3

#482 Allow multiple files to be sent with a message
  core/src/main/java/discord4j/core/spec/MessageCreateSpec.java
  rest/src/main/java/discord4j/rest/http/MultipartWriterStrategy.java
  rest/src/main/java/discord4j/rest/service/ChannelService.java
  rest/src/main/java/discord4j/rest/util/MultipartRequest.java
  rest/src/test/java/discord4j/rest/service/ChannelServiceTest.java
Labels: enhancement, v3

#479 Deprecate AudioReceiver
  core/src/main/java/discord4j/core/spec/VoiceChannelJoinSpec.java
  voice/src/main/java/discord4j/voice/AudioReceiver.java
Labels: v3

#493 Add convenience methods for spoiler attachments
  core/src/main/java/discord4j/core/object/entity/Attachment.java
  core/src/main/java/discord4j/core/spec/MessageCreateSpec.java
Labels: v3

#498 Change ChannelCreate, MessageDelete and TypingStart to use Nullable Long
  gateway/src/main/java/discord4j/gateway/json/dispatch/ChannelCreate.java
  gateway/src/main/java/discord4j/gateway/json/dispatch/MessageDelete.java
  gateway/src/main/java/discord4j/gateway/json/dispatch/TypingStart.java
Labels: v3

#459 Race Condition Fix on Guild Create
  src/main/java/sx/blah/discord/api/internal/DispatchHandler.java
Labels: v2

#499 Fix/immutable beans
  core/src/main/java/discord4j/core/event/dispatch/ChannelDispatchHandlers.java
  core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java
  core/src/main/java/discord4j/core/event/dispatch/MessageDispatchHandlers.java
  core/src/main/java/discord4j/core/object/data/stored/BaseGuildBean.java
  core/src/main/java/discord4j/core/object/data/stored/GuildBean.java
  core/src/main/java/discord4j/core/object/data/stored/MemberBean.java
  core/src/main/java/discord4j/core/object/data/stored/MessageBean.java
  core/src/main/java/discord4j/core/object/data/stored/ReactionBean.java
  core/src/main/java/discord4j/core/util/ArrayUtil.java
Labels: enhancement, v3
