Repository Discord4J/Discord4J, pull requests merged in 2022-10, with the labels that each got.

#1089 Replace TextChannel with MessageChannel in MessageBulkDeleteEvent
  core/src/main/java/discord4j/core/event/domain/message/MessageBulkDeleteEvent.java
Labels: area/core

#1097 Change implemenetations of `getX(id/name)` methods in application commands objects
  core/src/main/java/discord4j/core/object/command/ApplicationCommand.java
  core/src/main/java/discord4j/core/object/command/ApplicationCommandInteraction.java
  core/src/main/java/discord4j/core/object/command/ApplicationCommandInteractionOption.java
  core/src/main/java/discord4j/core/object/command/ApplicationCommandInteractionResolved.java
  core/src/main/java/discord4j/core/object/command/ApplicationCommandOption.java
Labels: enhancement

#1100 Fix Permission enum according to official discord doc
  rest/src/main/java/discord4j/rest/util/Permission.java
Labels: bug

#1101 Add support for new select menu components
  core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java
  core/src/main/java/discord4j/core/event/domain/interaction/SelectMenuInteractionEvent.java
  core/src/main/java/discord4j/core/object/component/MessageComponent.java
  core/src/main/java/discord4j/core/object/component/SelectMenu.java
  core/src/test/java/discord4j/core/ExampleSelectMenu.java
Labels: feature-request
