Repository Discord4J/Discord4J, pull requests merged in 2023-06, with the labels that each got.

#1134 Implement guild scheduled events
  build.gradle
  common/src/main/java/discord4j/common/JacksonResources.java
  common/src/main/java/discord4j/common/store/Store.java
  common/src/main/java/discord4j/common/store/action/gateway/GatewayActions.java
  common/src/main/java/discord4j/common/store/action/gateway/GuildScheduledEventCreateAction.java
  common/src/main/java/discord4j/common/store/action/gateway/GuildScheduledEventDeleteAction.java
  common/src/main/java/discord4j/common/store/action/gateway/GuildScheduledEventUpdateAction.java
  common/src/main/java/discord4j/common/store/action/gateway/GuildScheduledEventUserAddAction.java
  common/src/main/java/discord4j/common/store/action/gateway/GuildScheduledEventUserRemoveAction.java
  common/src/main/java/discord4j/common/store/action/read/GetGuildScheduledEventByIdAction.java
  common/src/main/java/discord4j/common/store/action/read/GetGuildScheduledEventUsersAction.java
  common/src/main/java/discord4j/common/store/action/read/GetGuildScheduledEventUsersInEventAction.java
  common/src/main/java/discord4j/common/store/action/read/GetGuildScheduledEventsInGuildAction.java
  common/src/main/java/discord4j/common/store/action/read/ReadActions.java
  common/src/main/java/discord4j/common/store/api/layout/DataAccessor.java
  common/src/main/java/discord4j/common/store/api/layout/GatewayDataUpdater.java
  common/src/main/java/discord4j/common/store/impl/LocalStoreLayout.java
  common/src/main/java/discord4j/common/store/legacy/LegacyStoreLayout.java
  common/src/main/java/discord4j/common/store/legacy/StateHolder.java
  core/src/main/java/discord4j/core/GatewayDiscordClient.java
  core/src/main/java/discord4j/core/event/ReactiveEventAdapter.java
  core/src/main/java/discord4j/core/event/dispatch/DispatchHandlers.java
  core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java
  core/src/main/java/discord4j/core/event/domain/guild/ScheduledEventCreateEvent.java
  core/src/main/java/discord4j/core/event/domain/guild/ScheduledEventDeleteEvent.java
  core/src/main/java/discord4j/core/event/domain/guild/ScheduledEventUpdateEvent.java
  core/src/main/java/discord4j/core/event/domain/guild/ScheduledEventUserAddEvent.java
  core/src/main/java/discord4j/core/event/domain/guild/ScheduledEventUserRemoveEvent.java
  core/src/main/java/discord4j/core/object/ScheduledEventEntityMetadata.java
  core/src/main/java/discord4j/core/object/ScheduledEventUser.java
  core/src/main/java/discord4j/core/object/audit/ActionType.java
  core/src/main/java/discord4j/core/object/audit/ChangeKey.java
  core/src/main/java/discord4j/core/object/entity/Guild.java
  core/src/main/java/discord4j/core/object/entity/ScheduledEvent.java
  core/src/main/java/discord4j/core/retriever/EntityRetriever.java
  core/src/main/java/discord4j/core/retriever/FallbackEntityRetriever.java
  core/src/main/java/discord4j/core/retriever/RestEntityRetriever.java
  core/src/main/java/discord4j/core/retriever/StoreEntityRetriever.java
  core/src/main/java/discord4j/core/spec/ScheduledEventCreateSpecGenerator.java
  core/src/main/java/discord4j/core/spec/ScheduledEventEditSpecGenerator.java
  core/src/main/java/discord4j/core/spec/ScheduledEventEntityMetadataSpecGenerator.java
  core/src/test/java/discord4j/core/ExampleGuildScheduledEvents.java
  gateway/src/main/java/discord4j/gateway/json/dispatch/EventNames.java
  gateway/src/main/java/discord4j/gateway/json/jackson/PayloadDeserializer.java
  gateway/src/main/java/discord4j/gateway/state/DispatchStoreLayer.java
  gradle.properties
  rest/src/main/java/discord4j/rest/RestClient.java
  rest/src/main/java/discord4j/rest/entity/RestGuild.java
  rest/src/main/java/discord4j/rest/entity/RestScheduledEvent.java
  rest/src/main/java/discord4j/rest/route/Routes.java
  rest/src/main/java/discord4j/rest/service/GuildService.java
Labels: feature-request

#1083 Add OAuth2 module
  oauth2/build.gradle
  oauth2/src/main/java/discord4j/oauth2/DiscordOAuth2Client.java
  oauth2/src/main/java/discord4j/oauth2/DiscordOAuth2Server.java
  oauth2/src/main/java/discord4j/oauth2/DiscordOAuth2SuccessHandler.java
  oauth2/src/main/java/discord4j/oauth2/Scope.java
  oauth2/src/main/java/discord4j/oauth2/object/AccessToken.java
  oauth2/src/main/java/discord4j/oauth2/service/OAuth2Service.java
  oauth2/src/test/java/discord4j/oauth2/ExampleOAuth2ClientCredentials.java
  oauth2/src/test/java/discord4j/oauth2/ExampleOAuth2CodeFlow.java
  rest/src/main/java/discord4j/rest/RestClientBuilder.java
  rest/src/main/java/discord4j/rest/RestResources.java
  rest/src/main/java/discord4j/rest/http/ExchangeStrategies.java
  rest/src/main/java/discord4j/rest/http/FormUrlEncodedWriterStrategy.java
  rest/src/main/java/discord4j/rest/http/client/AuthorizationScheme.java
  rest/src/main/java/discord4j/rest/http/client/ClientRequest.java
  rest/src/main/java/discord4j/rest/http/client/DiscordWebClient.java
  rest/src/main/java/discord4j/rest/request/DefaultRouter.java
  rest/src/main/java/discord4j/rest/request/DiscordWebRequest.java
  rest/src/main/java/discord4j/rest/request/RouterOptions.java
  rest/src/main/java/discord4j/rest/route/Routes.java
  settings.gradle
Labels: feature-request, area/rest

#1138 Mark the suppress-embeds Route as deprecated, along with all of its usages.
  core/src/main/java/discord4j/core/object/entity/Message.java
  rest/src/main/java/discord4j/rest/route/Routes.java
  rest/src/main/java/discord4j/rest/service/ChannelService.java
Labels: deprecation

#1128 Migration to reactor.util.retry.Retry after old retry deprecation (#1125)
  common/src/main/java/discord4j/common/retry/ReconnectContext.java
  rest/src/main/java/discord4j/rest/http/client/ClientException.java
  rest/src/main/java/discord4j/rest/request/RequestStream.java
  rest/src/main/java/discord4j/rest/response/ResponseFunction.java
  rest/src/main/java/discord4j/rest/response/RetryingTransformer.java
  rest/src/test/java/discord4j/rest/request/ClockGlobalRateLimiter.java
Labels: API change, behavior change

#1126 Implement forum channels
  core/src/main/java/discord4j/core/event/dispatch/ChannelDispatchHandlers.java
  core/src/main/java/discord4j/core/event/domain/channel/ForumChannelCreateEvent.java
  core/src/main/java/discord4j/core/event/domain/channel/ForumChannelDeleteEvent.java
  core/src/main/java/discord4j/core/event/domain/channel/ForumChannelUpdateEvent.java
  core/src/main/java/discord4j/core/object/entity/ForumTag.java
  core/src/main/java/discord4j/core/object/entity/Guild.java
  core/src/main/java/discord4j/core/object/entity/channel/Channel.java
  core/src/main/java/discord4j/core/object/entity/channel/ForumChannel.java
  core/src/main/java/discord4j/core/object/reaction/DefaultReaction.java
  core/src/main/java/discord4j/core/spec/ForumChannelCreateSpecGenerator.java
  core/src/main/java/discord4j/core/spec/ForumChannelEditSpecGenerator.java
  core/src/main/java/discord4j/core/spec/ForumTagCreateSpecGenerator.java
  core/src/main/java/discord4j/core/spec/ForumThreadMessageCreateSpecGenerator.java
  core/src/main/java/discord4j/core/spec/StartThreadInForumChannelSpecGenerator.java
  core/src/main/java/discord4j/core/util/EntityUtil.java
  core/src/test/java/discord4j/core/ExampleForum.java
  rest/src/main/java/discord4j/rest/route/Routes.java
  rest/src/main/java/discord4j/rest/service/ChannelService.java
  rest/src/main/java/discord4j/rest/util/AllowedMentions.java
Labels: feature-request

#1147 Add support for the new username system
  common/src/main/java/discord4j/common/store/impl/EmptyPartialUser.java
  common/src/main/java/discord4j/common/store/impl/EmptyUser.java
  common/src/main/java/discord4j/common/store/impl/LocalStoreLayout.java
  common/src/main/java/discord4j/common/store/legacy/LegacyStoreLayout.java
  core/src/main/java/discord4j/core/event/domain/PresenceUpdateEvent.java
  core/src/main/java/discord4j/core/object/entity/User.java
  core/src/main/java/discord4j/core/spec/legacy/LegacyUserEditSpec.java
  gradle.properties
Labels: deprecation

#1153 Propagate request cancellation to HttpClient
  .github/workflows/gradle.yml
  rest/src/main/java/discord4j/rest/request/DefaultRouter.java
  rest/src/main/java/discord4j/rest/request/RequestCorrelation.java
  rest/src/main/java/discord4j/rest/request/RequestStream.java
  rest/src/test/java/discord4j/rest/http/WebClientTest.java
Labels: bug
