Repository Discord4J/Discord4J, pull requests merged in 2023-05, with the labels that each got.

#1132 Update Gradlew Wrapper to 7.6.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: task

#1131 Implement Flags for Application
  core/src/main/java/discord4j/core/object/entity/ApplicationInfo.java
Labels: enhancement

#1145 fix(core): return proper values in `AutoModActionExecutedEvent` accessors
  core/src/main/java/discord4j/core/event/domain/automod/AutoModActionExecutedEvent.java
Labels: bug

#1146 feat(core): support delete_message_seconds in guild bans
  core/src/main/java/discord4j/core/spec/BanQuerySpecGenerator.java
Labels: deprecation
