Repository Discord4J/Discord4J, pull requests merged in 2024-04, with the labels that each got.

#1129 Fix unsigned long printing in requests (#1119)
  rest/src/main/java/discord4j/rest/util/RouteUtils.java
Labels: enhancement

#1161 Implement SuperReactions (Burst)
  common/src/main/java/discord4j/common/store/impl/LocalStoreLayout.java
  core/src/main/java/discord4j/core/object/reaction/Reaction.java
  core/src/main/java/discord4j/core/object/reaction/ReactionCountDetails.java
  gradle.properties
  rest/src/main/java/discord4j/rest/util/Color.java
  rest/src/test/java/discord4j/rest/util/ColorTest.java
Labels: area/core

#1176 Fix Jackson parsing in application commands when channels are DM channels
  core/src/main/java/discord4j/core/object/command/ResolvedChannel.java
  core/src/main/java/discord4j/core/object/command/ResolvedMember.java
Labels: API change
